[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "perongo"
version = "0.0.1"
description = "PKP timetable and delays mobile app"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Yehor Horin", email = "danedred@15@gmail.com" }]

dependencies = [
    "flet[all]",
    "requests",
    "python-dotenv",
]

[tool.uv]
prerelease = "disallow"

[tool.flet]
org = "org.daned.perongo"
product = "PeronGO"
company = "Yehor Horin"

[tool.flet.app]
path = "."