[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "perongo"
version = "0.2.5"
description = "PKP timetable and delays mobile app"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Yehor Horin", email = "danedred15@gmail.com" }]

dependencies = [
    "flet",
    "python-dotenv",
    "beautifulsoup4",
    "httpx",
]

[tool.uv]
prerelease = "allow"

[tool.flet]
org = "org.daned"
product = "PeronGO"
company = "Yehor Horin"

[tool.flet.app]
path = "."
assets = ["files"]

[tool.flet.icons]
android = "assets/icon.png"

[tool.flet.boot_screen.flet]
theme_mode = "auto"                       
bgcolor_light = "#ffffff"
bgcolor_dark = "#121212"                 
spinner_color_light = "#2196F3"
spinner_color_dark = "#2196F3"
spinner_size = 36                        
text_color_light = "#000000"
text_color_dark = "#ffffff"
prepare_message = "Przygotowywanie aplikacji..."
startup_message = "Uruchamianie..."

[tool.flet.flutter.pubspec.dependency_overrides]
flet = { git = { url = "https://github.com/flet-dev/flet.git", ref = "main", path = "packages/flet" } }